#ifndef EXTENDEDTABWIDGET_GLOBAL_H
#define EXTENDEDTABWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EXTENDEDTABWIDGET_LIBRARY)
#  define EXTENDEDTABWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define EXTENDEDTABWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EXTENDEDTABWIDGET_GLOBAL_H
